# -*- coding: utf-8 -*-
"""Google Sheets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6LaXSS11R3bQzo8IU5oYb2g-8ChyOcX
"""

import gspread
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text
import psycopg2

CREDENTIALS_FILE = "credentials.json"
GOOGLE_SHEET_URL = "https://docs.google.com/spreadsheets/d/1Y8OPOwEWrr2rOjcrMUnPdKlZTx-FbG70vR4GoAaKWqA/edit?usp=sharing"

gc_client = gspread.service_account(filename=CREDENTIALS_FILE)

workbook = gc_client.open_by_url(GOOGLE_SHEET_URL)

raw_data = dict()
for sheet in workbook.worksheets():
  records = sheet.get_all_values()
  if records:
     raw_data[sheet.title] = pd.DataFrame(data=records[1:], columns=records[0])

my_df = raw_data.get("Edwin-CF & CM")

my_df.head()







import gspread
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text
import psycopg2

# 3. Create the SQLAlchemy Engine
# Note: Use the 'postgresql+psycopg2://' dialect prefix
db_url = DB_URI
engine = create_engine(db_url)

SCHEMA_NAME = "energy"
TABLE_NAME = "edwin_cf_cm"

# 4. Create the Schema safely using a context manager
with engine.connect() as connection:
    # Executes raw SQL to build the schema if it is missing
    connection.execute(text(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA_NAME};"))
    # Commits the transaction block immediately
    connection.commit()

# --- Start of fix for ArgumentError ---
# Remove any columns that have empty string names or names that are just whitespace
# This often happens when reading from spreadsheets with blank header cells.
original_columns = my_df.columns.tolist()
my_df.columns = [str(col).strip() for col in my_df.columns] # Strip whitespace from column names

# Identify columns that became empty strings after stripping
empty_name_cols = [col for col in my_df.columns if col == '']
if empty_name_cols:
    print(f"Warning: Dropping columns with empty names: {original_columns[my_df.columns.tolist().index('')]}")
    my_df = my_df.loc[:, my_df.columns != '']

# Handle potential duplicate column names after stripping whitespace
# This ensures each column has a unique name before sending to SQL
my_df = my_df.loc[:, ~my_df.columns.duplicated()]
# --- End of fix for ArgumentError ---

# 5. Load the DataFrame and auto-create the table
my_df.to_sql(
    name=TABLE_NAME,
    con=engine,
    schema=SCHEMA_NAME,  # Targets your newly created schema
    if_exists="replace", # Options: 'fail', 'replace', or 'append'
    index=False,         # Prevents Pandas from writing the DataFrame index as a column
    chunksize=1000       # Optimizes memory by loading rows in batches
)

print(f"Success! Table '{SCHEMA_NAME}.{TABLE_NAME}' has been created and populated.")

empty_name_cols

pd.read_sql(f'SELECT * FROM energy.edwin_cf_cm', con=engine)
